name: Upload website data

on:
  push:
    branches:
      - main

jobs:
  upload_data:
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: hugo

      - name: Upload search data
        working-directory: ./algolia
        run: |
          npm install
          npm run data-upload -- -c \
            -f ../public/index.json \
            -a PKAF510SVG \
            -k ${{ secrets.ALGOLIA_ADMIN_API_KEY }} \
            -n emilien_website 

      - name: Deploy the website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: EmilienM/EmilienM.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: EmilienM
          user_email: emacchi@pm.me
