name: Upload website data
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  upload_data:
    runs-on: ubuntu-latest
    steps:
      - name: Update Git submodules remotely
        uses: runsascoded/update-submodules@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Site
        run: hugo --minify

      - name: Deploy the website
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: EmilienM/EmilienM.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: EmilienM
          user_email: emacchi@pm.me
